### ISSUE TITLE
Python Code Review

### ISSUE THREAD

**Issue by AladdinT** [Abdalla-Elsayed1/Embded-Systems-Diploma-Tasks#1]
### Session 1 

- Python/Session01/Task01/Basic Login script.py : You did not check if password matches the user, Using a dictionary to store username and password would be more convenient.

- Perfect Job with the rest

### Session 2

- Python/Session02/Quick_Tasks/find_largest_item.py : 1st solution is C style code, it is not recommended. The other solutions are more pythonic.

- The rest is perfect

#### Session 3

- Python/Session03/Task02/fl.py : line 10 :  In Python strings, backslashes are used as escape characters. 
	There are many work arrounds to add a path on windows , you figured one of them, the raw string r"".
```python
# double backslash 
firefox_path = "C:\\Program Files\\Mozilla Firefox\\firefox.exe"

# Using os module
import os
firefox_path = os.path.join("C:", "Program Files",  "Mozilla Firefox", "firefox.exe")
```
- Python/Important Tasks/Installing VScode etensions using pyautogui/fl.py : 'pyautogui.locateCenterOnScreen()' method returns the position of the located image , use this position in 'pyautogui.click(position.x , position.y)' instead of using magic numbers.

Please un-comment or remove commented code. Add a readme.md that describes repo content.
Great effort , Keep going :smile:

**Comment by Abdalla-Elsayed1** [comment]
Done, Thanks for feedback
